# Generated by Django 4.1.3 on 2022-12-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_encontrados_mail_encontrados_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='imagen_adopcion',
            field=models.ImageField(null=True, upload_to='adopcion'),
        ),
    ]
